### PR TITLE
Fix bug breaking file dialog

### PR DESCRIPTION
**Pull request by bcaddy**
If iseult was run from within its own repo the code would

1. Look for data files at pwd
2. If that failed it would look in pwd/flds,prtl,spec - this is where it was failing since there was no check if those subdirectories existed

I've fixed it so that now it checks it those subdirectories exist

### CODE REVIEW

**Comment by ntoles** [comment]
I get this error now if I try to start from Iseult install directory:

[16:21][anatoly@stellar-vis1 ~/tig/Bob-iseult]$ ./iseult.py 
Traceback (most recent call last):
  File "./iseult.py", line 60, in <module>
    from main_app import runMe
  File "./src/main_app.py", line 4, in <module>
    import data_loading # Allows us the read the data files
  File "./src/data_loading.py", line 212, in <module>
    def __handle_tristan_v2(file_path: pathlib.Path, file: h5py.File, dataset_name: str, dataset_slice: tuple | slice, cli_args: argparse.Namespace) -> np.ndarray | int | np.float64:
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Comment by bcaddy** [comment]
Are you using the `anaconda3/2023.9` module? What python version are you using?

That looks like an error from using python v3.9 or earlier. `anaconda3/2023.9` on Stellar should be Python 3.11.

**Comment by ntoles** [comment]
Ah, good point again. I have too many windows open with the old anaconda.
Now I get this error:

***@***.*** ~/tig/Bob-iseult][1]$ which python
/usr/licensed/anaconda3/2023.9/bin/python

***@***.*** ~/tig/Bob-iseult]$ git pull
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Total 4 (delta 3), reused 4 (delta 3), pack-reused 0
Unpacking objects: 100% (4/4), 1.53 KiB | 74.00 KiB/s, done.
From github.com:bcaddy/Iseult
   ae34820..3091548  master-tv2Spectra -> origin/master-tv2Spectra
Updating ae34820..3091548
Fast-forward
 tests/test_data_loading.py | 49
+++++++++++++++++++++++++++++++++++++++++++++----
 1 file changed, 45 insertions(+), 4 deletions(-)

***@***.*** ~/tig/Bob-iseult]$ ./iseult.py
Traceback (most recent call last):
  File "/tigress/anatoly/Bob-iseult/./iseult.py", line 61, in <module>
    runMe(cmd_args)
  File "/tigress/anatoly/Bob-iseult/./src/main_app.py", line 3557, in runMe
    app = MainApp('Iseult', cmd_args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tigress/anatoly/Bob-iseult/./src/main_app.py", line 1884, in
__init__
    self.findDir()
  File "/tigress/anatoly/Bob-iseult/./src/main_app.py", line 2312, in
findDir
    if not self.pathOK():
           ^^^^^^^^^^^^^
  File "/tigress/anatoly/Bob-iseult/./src/main_app.py", line 2210, in pathOK
    self.PathDict['Flds']= list(filter(f_re.match,
os.listdir(self.dirname+'/flds')))

 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './flds'

**Comment by bcaddy** [comment]
I think you ended up back on the `master-tv2Spectra` branch from PR #23 not the `master-bugfixFindingFiles` branch from this PR. I've already fixed that issue in the `master-tv2Spectra` branch, just pull the latest changes and you should be good.

**Pull request merged**
